In [4]:
import pandas as pd 
import numpy as np

In [2]:
#Series
#Creating series using a list

ps = pd.Series([1, 2, 3])
ps

0    1
1    2
2    3
dtype: int64

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
#Viewing series as an array
ps.values

array([1, 2, 3])

In [4]:
#labeling your series as per your own choice. you dont have this liberty in numpy
my_first_series = pd.Series([1, 2, 3], index = ['A', 'B', 'C'])
my_first_series

A    1
B    2
C    3
dtype: int64

In [5]:
my_first_series.index

Index(['A', 'B', 'C'], dtype='object')

In [7]:
#use index to access its value
my_first_series['A']

1

In [8]:
#manipulating the value of a series through an index
my_first_series['A'] = 100
my_first_series

A    100
B      2
C      3
dtype: int64

In [9]:
#Accessing subeset of series using indices
my_first_series[['A', 'C']]

A    100
C      3
dtype: int64

In [10]:
#filtering series using a condition
my_first_series[my_first_series > 5]

A    100
dtype: int64

In [11]:
my_first_series[my_first_series < 5]

B    2
C    3
dtype: int64

In [12]:
#Create a Series

my_first_series = pd.Series(np.arange(10))
my_first_series

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [13]:
#creating a series using a tuple
my_first_series = pd.Series((1, 2, 3, 4, 5, 6))
my_first_series

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [9]:
#creating a series using a dictionary. Keys are inferred as indices. 
my_first_series = pd.Series({'John' : 34, 'Jim' : 30, 'Sara' : 26, 'Anil' : 40, 'Majid' : 38})
my_first_series

John     34
Jim      30
Sara     26
Anil     40
Majid    38
dtype: int64

In [10]:
my_first_series.John

34

In [16]:
my_first_series['Majid']

38

In [12]:
#DataFrame
#Create a dataframe using a dictionary

data = {"Name" : ['Ohio', 'Ontario', 'London', 'Paris', 'Melbourne', 'Delhi', 'Beijing'],
        "year" : [2020, 2023, 2019, 2018, 2010, 1999, 1996],
        "cases" :[34, 12, 50, 30, 49, 190, 80]}
data

{'Name': ['Ohio',
  'Ontario',
  'London',
  'Paris',
  'Melbourne',
  'Delhi',
  'Beijing'],
 'year': [2020, 2023, 2019, 2018, 2010, 1999, 1996],
 'cases': [34, 12, 50, 30, 49, 190, 80]}

In [14]:
#A 2-d data structure labeled at both the dimensions. 
my_first_dataframe = pd.DataFrame(data, index = ['A', 'B', 'C', 'D', 'E', 'F', 'G'])
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D      Paris  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [19]:
#just see top 5 values
my_first_dataframe.head()

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D      Paris  2018     30
E  Melbourne  2010     49

In [20]:
#just display bottom fove values
my_first_dataframe.tail()

Name  year  cases
C     London  2019     50
D      Paris  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [21]:
#dataframe in a certain order
pd.DataFrame(data, columns = ['year', 'Name', 'cases'])

year       Name  cases
0  2020       Ohio     34
1  2023    Ontario     12
2  2019     London     50
3  2018      Paris     30
4  2010  Melbourne     49
5  1999      Delhi    190
6  1996    Beijing     80

In [22]:
#access a column
my_first_dataframe['Name']

A         Ohio
B      Ontario
C       London
D        Paris
E    Melbourne
F        Delhi
G      Beijing
Name: Name, dtype: object

In [23]:
#access a row by the name of the index
my_first_dataframe.loc['G']

Name     Beijing
year        1996
cases         80
Name: G, dtype: object

In [24]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D      Paris  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [25]:
#Accessing a particular element requires selecting a column and the index
my_first_dataframe['Name']['D']

'Paris'

In [26]:
#Replacing a particular value in dataframe
my_first_dataframe['Name']['D'] = 'Durham'
my_first_dataframe

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D     Durham  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [27]:
#Delete or drop a row or a column

my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D     Durham  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [28]:
#Lets say want to drop 4th index

my_first_dataframe.drop('D')

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [29]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
D     Durham  2018     30
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [51]:
#The drop method just temporarily drops and shows you a view of it. In actual its not dropped

my_first_dataframe.drop('D', inplace = True)

In [52]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [32]:
#what if you want to drop a column

my_first_dataframe.drop('year', axis = 1)

Name  cases
A       Ohio     34
B    Ontario     12
C     London     50
E  Melbourne     49
F      Delhi    190
G    Beijing     80

In [33]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [34]:
#Access via filtering over a condition on one column
my_first_dataframe[my_first_dataframe['cases'] < 50]

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
E  Melbourne  2010     49

In [35]:
my_first_dataframe[my_first_dataframe['year'] > 2015]

Name  year  cases
A     Ohio  2020     34
B  Ontario  2023     12
C   London  2019     50

In [36]:
#Accessing using multiple conditions
my_first_dataframe[((my_first_dataframe['year'] > 2015) & (my_first_dataframe['cases'] > 30))]

Name  year  cases
A    Ohio  2020     34
C  London  2019     50

In [37]:
#Sorting

my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [38]:
my_new_dataframe = my_first_dataframe.set_index('year')
my_new_dataframe

Name  cases
year                  
2020       Ohio     34
2023    Ontario     12
2019     London     50
2010  Melbourne     49
1999      Delhi    190
1996    Beijing     80

In [39]:
my_new_dataframe.sort_index(ascending=True)

Name  cases
year                  
1996    Beijing     80
1999      Delhi    190
2010  Melbourne     49
2019     London     50
2020       Ohio     34
2023    Ontario     12

In [40]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [41]:
#Sorting without setting an index
my_first_dataframe.sort_values('year')

Name  year  cases
G    Beijing  1996     80
F      Delhi  1999    190
E  Melbourne  2010     49
C     London  2019     50
A       Ohio  2020     34
B    Ontario  2023     12

In [42]:
my_first_dataframe.sort_values(['Name','year'])

Name  year  cases
G    Beijing  1996     80
F      Delhi  1999    190
C     London  2019     50
E  Melbourne  2010     49
A       Ohio  2020     34
B    Ontario  2023     12

In [43]:
my_first_dataframe

Name  year  cases
A       Ohio  2020     34
B    Ontario  2023     12
C     London  2019     50
E  Melbourne  2010     49
F      Delhi  1999    190
G    Beijing  1996     80

In [45]:
my_first_dataframe[['cases']].sum()

cases    415
dtype: int64

In [46]:
my_first_dataframe[['cases']].mean()

cases    69.166667
dtype: float64

In [47]:
np.random.randint(5, size = (7))

array([0, 1, 1, 1, 2, 1, 0])

In [53]:
#Add a column to an existing dataframe
my_first_dataframe['group'] = np.random.randint(5, size = (6))
my_first_dataframe

Name  year  cases  group
A       Ohio  2020     34      0
B    Ontario  2023     12      1
C     London  2019     50      0
E  Melbourne  2010     49      2
F      Delhi  1999    190      2
G    Beijing  1996     80      4

In [54]:
#unique values in a column
my_first_dataframe['group'].unique()

array([0, 1, 2, 4])

In [55]:
#frequency of the column
my_first_dataframe['group'].value_counts()

2    2
0    2
4    1
1    1
Name: group, dtype: int64

Create a dataframe from a dictionary where the keys are the names of countries, the values are the gdp and indices are last 10 years. 
Now try to find the average gdp combined for all countries over past 10 years. 

In [1]:
# Create a dictionary with country names as keys and GDP data as values
data = {
    'USA': [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
    'China': [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
    'India': [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
}

In [2]:
data

{'USA': [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
 'China': [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
 'India': [300, 310, 320, 330, 340, 350, 360, 370, 380, 390]}

In [5]:
data = pd.DataFrame(data, index = [str(2023 - i) for i in range(10)])
data

USA  China  India
2023  100    200    300
2022  110    210    310
2021  120    220    320
2020  130    230    330
2019  140    240    340
2018  150    250    350
2017  160    260    360
2016  170    270    370
2015  180    280    380
2014  190    290    390

In [6]:
# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Calculate the average GDP across all countries over the past 10 years
average_gdp_combined = df.mean().mean()